### ISSUE TITLE
allow -999 option to turn off 5th and 6th parameters in double normal

### ISSUE THREAD

**Issue by iantaylor-NOAA** [r4ss/shiny_selex#5]
It's common not to use all 6 double-normal parameters.
 The underlying code to plot the function already supports -999 values, but the user has no control to use that option. The old tcl/tk widget in r4ss had a really broad range to allow users to select -999, but that makes the 0 to 1 range too small. A better alternative would be a check box or button to select -999 instead of providing a value in the 0 to 1 range.

**Comment by k-doering-NOAA** [comment]
This was done by adding check boxes and graying out the slider/numeric input options.

The -999 values definitely result in a change in the curve, but I didn't double check that the code is processing it properly - there are a lot of if() statements that i couldn't easily follow. It would be worth checking it against the r4ss functons and function in ss.
